name: drug_shoppa
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  api_cache_manager: ^1.0.2
  auto_size_text: ^3.0.0
  carousel_slider: ^4.1.1
  convex_bottom_bar: ^3.0.0
  curved_navigation_bar: ^1.0.3
  dots_indicator: ^2.1.0
  flutter:
    sdk: flutter
  flutter_conditional_rendering: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_lints: ^1.0.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  icons_launcher: ^1.1.8
  iconsax: ^0.0.8
  local_auth: ^2.1.0
  pull_to_refresh: ^2.0.0
  snippet_coder_utils: ^1.0.12
  toggle_switch: ^2.0.1
  transparent_image: ^2.0.0
  url_launcher: ^6.1.3
  water_drop_nav_bar: ^2.2.0+3
  page_view_indicators: ^2.0.0
  flutter_secure_storage_web: ^1.0.2
  shared_preferences_web: ^2.0.4
  alice: ^0.2.5
  dio: ^4.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: 'assets/DrugShoppa-icon.png'
  ios: true
  android: true
flutter:
  uses-material-design: true
  assets:
      - assets/splashbgportrait.png
      - assets/splashbg.png
      - assets/DrugShoppa-1-1.png
      - assets/DrugShoppa-1-1wrapped.png
      - assets/boy.png
      - assets/bell.png
      - assets/whatsapp.png
      - assets/phone-call.png
      - assets/buyairtimeanddata.png
      - assets/paybillsandfees.png
      - assets/pills.png
      - .env
